### ISSUE TITLE
user stories

### ISSUE THREAD

**Issue by YannEndezUGA** [2023-2024-ECOM-INFO5-G2/docs#5]
Faut t 'il préparer user stories pour la soutenance de pré-étude ?
@SybilleCaffiau

**Comment by SybilleCaffiau** [comment]
Il faut que vous préparer tout votre sprint 1 donc au moins les US du sprint 1 oui

**Comment by Eloiii** [comment]
Doit-on créer des personas (acteurs et utilisateurs types), si oui à quel niveau de détail ?

**Comment by SybilleCaffiau** [comment]
Réponse enseignant : Oui. Il faudra en faire mais reposez moi la question vendredi, nous verrons les persona en cours.
