### ISSUE TITLE
Question vue(s) dynamique(s)

### ISSUE THREAD

**Issue by Eloiii** [2023-2024-ECOM-INFO5-G2/docs#7]
Doit-on faire une seule vue dynamique globale entre nos acteurs et composants (par exemple le médecin interagit avec le frontend relié au backend relié à la base de données) ? Ou doit-on réaliser plusieurs vues dynamiques pour plusieurs cas (consultation du dossier d'un résident, modification ou ajout d'un patient...) ? @SybilleCaffiau

**Comment by SybilleCaffiau** [comment]
labellisez votre question pou que je sache si c'est à l'enseignant u au client que vous vous adressez svp

**Comment by Eloiii** [comment]
@SybilleCaffiau

**Comment by SybilleCaffiau** [comment]
Si votre définition d'une vue dynamique est la mienne (1 vue = 1 écran) rien ne vous empêche d'en faire plusieurs. Je vous conseille d'ailleurs de décomposer 1 vue/écran par grande tâche utilisateur. Si votre définition est différente, pourriez vous me préciser ce que vous entendez par vue dynamique ?
